<?php
require_once 'db_config.php';
require_once '../includes/settings_helper.php';

// Get settings
$site_title = getSetting('site_title');
$site_description = getSetting('site_description');
$footer_text = getSetting('footer_text');
$instagram_url = getSetting('instagram_url');
$facebook_url = getSetting('facebook_url');
$twitter_url = getSetting('twitter_url');
$linkedin_url = getSetting('linkedin_url');

// Get all events with ratings
$sql = "SELECT e.*, 
    COALESCE(AVG(f.rating), 0) as avg_rating,
    COUNT(f.id) as feedback_count
    FROM events e 
    LEFT JOIN event_feedback f ON e.id = f.event_id 
    GROUP BY e.id 
    ORDER BY e.event_date DESC";
$result = $conn->query($sql);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events - IT Club</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Animated Background -->
    <ul class="bg-animation">
        <!-- Bubbles will be generated by JavaScript -->
    </ul>
    
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="index.php">
                <img src="it-club-logo.png" alt="IT Club Logo" height="50">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <div class="hamburger-lines">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.php#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.php#features">Features</a></li>
                    <li class="nav-item"><a class="nav-link active" href="events.php">Events</a></li>
                    <li class="nav-item"><a class="nav-link" href="winners.php">Winners</a></li>
                    <li class="nav-item"><a class="nav-link" href="contact.php">Contact</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                            Login
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="login.php?role=faculty">Faculty Login</a></li>
                            <li><a class="dropdown-item" href="login.php?role=member">Member Login</a></li>
                        </ul>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <section class="page-header text-center">
        <div class="container">
            <h1 style="color: #fff;">Events</h1>
            <p class="lead" style="color: #fff;">Discover our upcoming and past events</p>
        </div>
    </section>

    <!-- Events Section -->
    <section class="events-preview py-5">
        <div class="container">
            <h2 class="section-title text-center">Browse Events</h2>
            <div class="row mb-4">
                <div class="col-md-12 text-center">
                    <div class="btn-group" role="group" aria-label="Event filters">
                        <button type="button" class="btn filter-btn active" data-filter="all">All Events</button>
                        <button type="button" class="btn filter-btn" data-filter="upcoming">Upcoming Events</button>
                        <button type="button" class="btn filter-btn" data-filter="past">Past Events</button>
                    </div>
                </div>
            </div>
            
            <div class="row" id="events-container">
                <?php 
                if ($result->num_rows > 0) {
                    while($row = $result->fetch_assoc()) {
                        $event_date = strtotime($row['event_date']);
                        $is_past = $event_date < time() ? 'past' : 'upcoming';
                ?>
                <div class="col-md-4 mb-4 event-item <?php echo $is_past; ?>" data-aos="fade-up">
                    <div class="card h-100 event-card">
                        <img src="../<?php echo htmlspecialchars($row['image']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($row['title']); ?>">
                        <div class="card-body">
                            <h5 class="card-title" style="color: #fff;"><?php echo htmlspecialchars($row['title']); ?></h5>
                            <p class="card-text" style="color: #fff;"><i class="far fa-calendar-alt me-2"></i><?php echo date('F d, Y', $event_date); ?></p>
                            <p class="card-text"><i class="fas fa-map-marker-alt me-2"></i><?php echo htmlspecialchars($row['location']); ?></p>
                            <p class="card-text">
                                <i class="fas fa-money-bill-wave me-2"></i>
                                <?php if (isset($row['is_paid']) && $row['is_paid']): ?>
                                    <span class="badge bg-warning text-dark">₹<?php echo number_format($row['price'], 2); ?></span>
                                <?php else: ?>
                                    <span class="badge bg-success">Free</span>
                                <?php endif; ?>
                            </p>
                            <?php if ($is_past == 'past' && isset($row['feedback_count']) && $row['feedback_count'] > 0): ?>
                                <p class="card-text">
                                    <i class="fas fa-star text-warning me-1"></i>
                                    <span class="fw-bold text-warning"><?php echo number_format($row['avg_rating'], 1); ?></span>
                                </p>
                            <?php endif; ?>
                            <a href="event_details.php?id=<?php echo $row['id']; ?>" class="btn btn-sm btn-primary">Learn More</a>
                        </div>
                    </div>
                </div>
                <?php 
                    }
                } else {
                    echo '<div class="col-12 text-center"><p>No events found. Check back soon for upcoming events!</p></div>';
                }
                ?>
            </div>
        </div>
    </section>

<?php include 'footer.php'; ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize AOS animation library
            AOS.init({
                duration: 600,
                easing: 'ease-out',
                once: true,
                offset: 50,
                disable: false
            });

            // Navbar scroll effect
            window.addEventListener('scroll', function() {
                const navbar = document.querySelector('.navbar');
                if (window.scrollY > 50) {
                    navbar.classList.add('scrolled');
                } else {
                    navbar.classList.remove('scrolled');
                }
            });

            // Animated background bubbles
            const bgAnimation = document.querySelector('.bg-animation');
            if (bgAnimation) {
                for (let i = 0; i < 15; i++) {
                    const li = document.createElement('li');
                    const size = Math.random() * 80 + 20;
                    const position = Math.random() * 100;
                    const delay = Math.random() * 2;
                    const duration = Math.random() * 15 + 8;

                    li.style.width = `${size}px`;
                    li.style.height = `${size}px`;
                    li.style.left = `${position}%`;
                    li.style.animationDelay = `${delay}s`;
                    li.style.animationDuration = `${duration}s`;
                    li.style.animationTimingFunction = `cubic-bezier(${Math.random()}, ${Math.random()}, ${Math.random()}, ${Math.random()})`;

                    bgAnimation.appendChild(li);
                }
            }

            // Event filtering
            document.querySelectorAll('.filter-btn').forEach(button => {
                button.addEventListener('click', function() {
                    // Remove active class from all buttons
                    document.querySelectorAll('.filter-btn').forEach(btn => {
                        btn.classList.remove('active');
                    });

                    // Add active class to clicked button
                    this.classList.add('active');

                    const filterValue = this.getAttribute('data-filter');

                    // Show/hide events based on filter
                    document.querySelectorAll('.event-item').forEach(item => {
                        if (filterValue === 'all') {
                            item.style.display = 'block';
                        } else if (item.classList.contains(filterValue)) {
                            item.style.display = 'block';
                        } else {
                            item.style.display = 'none';
                        }
                    });
                });
            });
        });
    </script>
</body>
</html>
<?php $conn->close(); ?>