<?php
require_once 'db_config.php';
require_once '../includes/settings_helper.php';

// Get website settings
$site_title = getSetting('site_title');
$site_description = getSetting('site_description');
$college_name = getSetting('college_name');
$department_name = getSetting('department_name');
$about_text = getSetting('about_text');
$footer_text = getSetting('footer_text');
$contact_email = getSetting('contact_email');
$contact_phone = getSetting('contact_phone');
$instagram_url = getSetting('instagram_url');
$facebook_url = getSetting('facebook_url');
$twitter_url = getSetting('twitter_url');
$linkedin_url = getSetting('linkedin_url');

// Get upcoming events
$sql = "SELECT * FROM events WHERE event_date >= CURDATE() ORDER BY event_date ASC LIMIT 3";
$result = $conn->query($sql);

// Get past events with ratings
$sql_past = "SELECT e.*, 
    COALESCE(AVG(f.rating), 0) as avg_rating,
    COUNT(f.id) as feedback_count
    FROM events e 
    LEFT JOIN event_feedback f ON e.id = f.event_id 
    WHERE e.event_date < CURDATE() 
    GROUP BY e.id 
    ORDER BY e.event_date DESC LIMIT 3";
$result_past = $conn->query($sql_past);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($site_title); ?> - <?php echo htmlspecialchars($college_name); ?></title>
    <meta name="description" content="<?php echo htmlspecialchars($site_description); ?>">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <!-- AOS Animation Library -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Animated Background -->
    <ul class="bg-animation">
        <!-- Bubbles will be generated by JavaScript -->
    </ul>
    
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="#">
               <img src="it-club-logo.png" alt="IT Club Logo" height="50">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <div class="hamburger-lines">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link active" href="#home">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#features">Features</a></li>
                    <li class="nav-item"><a class="nav-link" href="events.php">Events</a></li>
                    <li class="nav-item"><a class="nav-link" href="winners.php">Winners</a></li>
                    <li class="nav-item"><a class="nav-link" href="contact.php">Contact</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button">
                            Login
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="login.php?role=faculty">Faculty Login</a></li>
                            <li><a class="dropdown-item" href="login.php?role=member">Member Login</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section id="home" class="hero text-center">
        <div class="container">
            <p data-aos="fade-down">
            <img src="college logo.png" alt="College Logo" height="150" width="auto" style="margin-right:12px; max-width:100%;">
            </p>
            <h1 data-aos="fade-down" data-aos-duration="1000"><?php echo strtoupper(htmlspecialchars($college_name)); ?></h1><h2 data-aos="fade-up"><?php echo htmlspecialchars($site_title); ?></h2>
            <p class="lead" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200"><?php echo htmlspecialchars($site_description); ?></p>
            <div data-aos="zoom-in" data-aos-duration="1000" data-aos-delay="300">
                <a href="events.php" class="btn btn-primary me-3">Explore Events</a>
                <a href="#about" class="btn btn-outline-light">Learn More</a>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about" class="about py-5">
        <div class="container">
            <h2 class="section-title text-center">About IT Club</h2>
            <div class="row align-items-center mb-5">
                <div class="col-lg-6" data-aos="fade-right" data-aos-duration="1000">
                    <p>The IT Club of Sangameshwar College, established in 2024, is a dynamic student-driven initiative aimed at fostering curiosity, innovation, and collaboration in the field of Information Technology. With a strong foundation in technical knowledge and an inclusive environment, the club serves as a hub for students passionate about coding, software development, cybersecurity, networking, AI, and the ever-evolving tech landscape.</p>
                    <div class="mt-4">
                        <h4 style="color: var(--primary-color);">Our Vision</h4>
                        <p>To become a leading student community that empowers young minds to explore, learn, and innovate in the field of Information Technology. We strive to bridge the gap between academic learning and real-world applications.</p>
                    </div>
                </div>
                <div class="col-lg-6" data-aos="fade-left" data-aos-duration="1000" data-aos-delay="200">
                    <img src="https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80" class="img-fluid rounded shadow" alt="IT Club Team" style="height:300px; width:100%; object-fit:cover;">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
                    <div class="text-center p-4">
                        <h4 style="color: var(--accent-color);">Our Motto</h4>
                        <h3 style="color: var(--primary-color);">"Learn. Build. Lead."</h3>
                        <p>We believe in continuous learning, practical implementation, and leadership through technology.</p>
                    </div>
                </div>
                <div class="col-lg-8" data-aos="fade-up" data-aos-delay="200">
                    <h4 style="color: var(--primary-color);">Shaping Students' Futures</h4>
                    <p>The IT Club actively organizes workshops, coding challenges, expert sessions, industrial visits, tech talks, and mini-project exhibitions. These initiatives help students stay updated with the latest industry trends, enhance their problem-solving abilities, and build a strong portfolio.</p>
                    <p>Whether a beginner or an advanced learner, every student finds opportunities for personal and professional growth. Students gain not just technical knowledge but also leadership qualities, teamwork experience, and project management skills—making them industry-ready and future-focused professionals.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Features Section -->
    <section id="features" class="features py-5 bg-light">
        <div class="container">
            <h2 class="section-title text-center">What We Offer</h2>
            <div class="row">
                <div class="col-md-4" data-aos="fade-up" data-aos-duration="800">
                    <div class="feature-box">
                        <div class="feature-icon">
                            <i class="fas fa-laptop-code"></i>
                        </div>
                        <h3>Workshops</h3>
                        <p>Hands-on learning experiences led by industry experts and experienced peers.</p>
                    </div>
                </div>
                <div class="col-md-4" data-aos="fade-up" data-aos-duration="800" data-aos-delay="200">
                    <div class="feature-box">
                        <div class="feature-icon">
                            <i class="fas fa-trophy"></i>
                        </div>
                        <h3>Hackathons</h3>
                        <p>Competitive events to showcase your skills and win exciting prizes.</p>
                    </div>
                </div>
                <div class="col-md-4" data-aos="fade-up" data-aos-duration="800" data-aos-delay="400">
                    <div class="feature-box">
                        <div class="feature-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <h3>Networking</h3>
                        <p>Connect with peers, alumni, and industry professionals in the tech field.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Upcoming Events Preview -->
    <?php if ($result->num_rows > 0): ?>
    <section class="events-preview py-5">
        <div class="container">
            <h2 class="section-title text-center">Upcoming Events</h2>
            <div class="row" id="events-preview">
                <?php 
                    while($row = $result->fetch_assoc()) {
                ?>
                <div class="col-md-4 mb-4" data-aos="fade-up">
                    <div class="card h-100 event-card">
                        <img src="../<?php echo htmlspecialchars($row['image']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($row['title']); ?>">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo htmlspecialchars($row['title']); ?></h5>
                            <p class="card-text"><i class="far fa-calendar-alt me-2"></i><?php echo date('F d, Y', strtotime($row['event_date'])); ?></p>
                            <p class="card-text"><i class="fas fa-map-marker-alt me-2"></i><?php echo htmlspecialchars($row['location']); ?></p>
                            <p class="card-text">
                                <i class="fas fa-money-bill-wave me-2"></i>
                                <?php if (isset($row['is_paid']) && $row['is_paid']): ?>
                                    <span class="badge bg-warning text-dark">₹<?php echo number_format($row['price'], 2); ?></span>
                                <?php else: ?>
                                    <span class="badge bg-success">Free</span>
                                <?php endif; ?>
                            </p>
                            <a href="event_details.php?id=<?php echo $row['id']; ?>" class="btn btn-sm btn-primary">Learn More</a>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </section>
    <?php endif; ?>

    <!-- Past Events Preview -->
    <?php if ($result_past->num_rows > 0): ?>
    <section class="events-preview py-5">
        <div class="container">
            <h2 class="section-title text-center">Past Events</h2>
            <div class="row" id="past-events-preview">
                <?php 
                    while($row = $result_past->fetch_assoc()) {
                ?>
                <div class="col-md-4 mb-4" data-aos="fade-up">
                    <div class="card h-100 event-card">
                        <img src="../<?php echo htmlspecialchars($row['image']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($row['title']); ?>">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo htmlspecialchars($row['title']); ?></h5>
                            <p class="card-text"><i class="far fa-calendar-alt me-2"></i><?php echo date('F d, Y', strtotime($row['event_date'])); ?></p>
                            <p class="card-text"><i class="fas fa-map-marker-alt me-2"></i><?php echo htmlspecialchars($row['location']); ?></p>
                            <?php if ($row['avg_rating'] > 0): ?>
                                <p class="card-text">
                                    <i class="fas fa-star text-warning me-1"></i>
                                    <span class="fw-bold text-warning"><?php echo number_format($row['avg_rating'], 1); ?></span>
                                </p>
                            <?php endif; ?>
                            <a href="event_details.php?id=<?php echo $row['id']; ?>" class="btn btn-sm btn-secondary">Browse Event</a>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </section>
    <?php endif; ?>
    
    <?php if ($result->num_rows > 0 || $result_past->num_rows > 0): ?>
    <section class="py-3">
        <div class="container">
            <div class="text-center mt-4" data-aos="fade-up">
                <a href="events.php" class="btn btn-primary">View All Events</a>
            </div>
        </div>
    </section>
    <?php endif; ?>

    <!-- Testimonials -->
    <section class="testimonials py-5 bg-light">
        <div class="container">
            <h2 class="section-title text-center">What Our Members Say</h2>
            <div class="row">
                <div class="col-md-4" data-aos="fade-up">
                    <div class="testimonial-card">
                        <div class="testimonial-content">
                            <p>"The IT Club workshops helped me gain practical skills that I couldn't learn in regular classes. Highly recommended!"</p>
                        </div>
                        <div class="testimonial-author">
                            <h5>President</h5>
                            <h5>Ayush Teke</h5>
                            <p>BCA, 2<sup>nd</sup> Year</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4" data-aos="fade-up" data-aos-delay="200">
                    <div class="testimonial-card">
                        <div class="testimonial-content">
                            <p>"Participating in the hackathon organized by IT Club was a game-changer for my career. I got an internship through the connections I made!"</p>
                        </div>
                        <div class="testimonial-author">
                            <h5>Vice President</h5>
                            <h5>Rucha Sanlunkhe</h5>
                            <p>BCS, 3<sup>rd</sup> Year</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4" data-aos="fade-up" data-aos-delay="400">
                    <div class="testimonial-card">
                        <div class="testimonial-content">
                            <p>"The community at IT Club is amazing. I've made great friends and learned so much from the collaborative environment."</p>
                        </div>
                        <div class="testimonial-author">
                            <h5>Secretary</h5>
                            <h5>Aditya Patil</h5>
                            <p>BCA, 3<sup>rd</sup> Year</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Call to Action -->
    <section class="cta py-5 text-center text-white">
        <div class="container">
            <h2 data-aos="fade-down">Want to share your IT skills?</h2>
            <!-- <p data-aos="fade-up" data-aos-delay="200">Become a member today and start your journey with IT Club!</p> -->
            <a href="contact.php" class="btn btn-light btn-lg" data-aos="zoom-in" data-aos-delay="400">Share Now</a>
        </div>
    </section>

<?php include 'footer.php'; ?>

    <script src="optimize.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" defer></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Fix mobile dropdown
            const dropdownToggle = document.querySelector('.dropdown-toggle');
            const dropdownMenu = document.querySelector('.dropdown-menu');
            
            if (dropdownToggle && dropdownMenu) {
                dropdownToggle.addEventListener('click', function(e) {
                    e.preventDefault();
                    e.stopPropagation();
                    dropdownMenu.classList.toggle('show');
                });
                
                document.addEventListener('click', function(e) {
                    if (!dropdownToggle.contains(e.target) && !dropdownMenu.contains(e.target)) {
                        dropdownMenu.classList.remove('show');
                    }
                });
            }
            
            // Initialize AOS animation library - Optimized
            AOS.init({
                duration: 600,
                easing: 'ease-out',
                once: true,
                offset: 50,
                disable: false
            });

            // Enhanced navbar scroll behavior
            let lastScrollTop = 0;
            const navbar = document.querySelector('.navbar');
            
            window.addEventListener('scroll', function() {
                const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
                
                if (scrollTop > 50) {
                    navbar.classList.add('scrolled');
                } else {
                    navbar.classList.remove('scrolled');
                }
                
                // Auto-hide navbar on mobile when scrolling down
                if (window.innerWidth <= 991) {
                    if (scrollTop > lastScrollTop && scrollTop > 100) {
                        navbar.style.transform = 'translateY(-100%)';
                    } else {
                        navbar.style.transform = 'translateY(0)';
                    }
                }
                
                lastScrollTop = scrollTop;
            }, { passive: true });
            
            // Seamless mobile menu handling
            const navbarToggler = document.querySelector('.navbar-toggler');
            const navbarCollapse = document.querySelector('.navbar-collapse');
            
            // Close mobile menu when clicking outside
            document.addEventListener('click', function(event) {
                if (!navbar.contains(event.target) && navbarCollapse.classList.contains('show')) {
                    navbarToggler.click();
                }
            });
            
            // Close menu when clicking nav links (except dropdown)
            document.querySelectorAll('.nav-link:not(.dropdown-toggle)').forEach(link => {
                link.addEventListener('click', () => {
                    if (navbarCollapse.classList.contains('show')) {
                        navbarToggler.click();
                    }
                });
            });

            // Smooth scrolling for anchor links
            document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                anchor.addEventListener('click', function(e) {
                    e.preventDefault();
                    const targetId = this.getAttribute('href');
                    if (targetId === '#') return;
                    
                    const targetElement = document.querySelector(targetId);
                    if (targetElement) {
                        window.scrollTo({
                            top: targetElement.offsetTop - 70,
                            behavior: 'smooth'
                        });
                    }
                });
            });

            // Animated background bubbles - Optimized
            const bgAnimation = document.querySelector('.bg-animation');
            if (bgAnimation) {
                const fragment = document.createDocumentFragment();
                for (let i = 0; i < 10; i++) {
                    const li = document.createElement('li');
                    const size = Math.random() * 60 + 20;
                    const position = Math.random() * 100;
                    const delay = Math.random() * 2;
                    const duration = Math.random() * 10 + 15;
                    
                    li.style.cssText = `width:${size}px;height:${size}px;left:${position}%;animation-delay:${delay}s;animation-duration:${duration}s`;
                    
                    fragment.appendChild(li);
                }
                bgAnimation.appendChild(fragment);
            }
        });
        
        // Back to Top Button functionality
        const backToTopButton = document.getElementById('backToTop');
        
        window.addEventListener('scroll', () => {
            if (window.pageYOffset > 300) {
                backToTopButton.classList.add('show');
            } else {
                backToTopButton.classList.remove('show');
            }
        });
        
        backToTopButton.addEventListener('click', (e) => {
            e.preventDefault();
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    </script>
</body>
</html>
<?php $conn->close(); ?>